<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>WmsService.Application</AssemblyName>
    <RootNamespace>WmsService.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WmsService.Domain\WmsService.Domain.csproj" />
  </ItemGroup>

</Project>
